"""empty message

Revision ID: 2be3ae4616fe
Revises: b8f831cd793f
Create Date: 2020-09-25 01:48:37.209916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be3ae4616fe'
down_revision = 'b8f831cd793f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tribal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tribal_tribe_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tribal_tribe_name')
    )
    op.add_column('users', sa.Column('tribal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tribal')
    op.drop_table('tribal')
    # ### end Alembic commands ###
