"""empty message

Revision ID: b8f831cd793f
Revises: c95fb3704a72
Create Date: 2020-09-25 00:19:48.735833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f831cd793f'
down_revision = 'c95fb3704a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('round', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'round')
    # ### end Alembic commands ###
